bank-system event store
DoKep2/ppo-y2023 pull request #2
Opened 2023-11-16 15:52 UTC by DoKep2

2023-11-20 13:27 UTC, DoKep2 commented
@fadyat rd 4 review, mb some comments about api naming
todo's with logging will be fixed soon :/

2023-11-20 16:58 UTC, fadyat requested changes
write some tests for your API

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/aggregates/AccountAggregateState.kt
> +    var updatedAt: Long = System.currentTimeMillis()
I think all of the attributes should be nullable by default (`lateinit` probably)

because first AccountAggregateState is an EmptyState

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/aggregates/AccountAggregateState.kt
> +// Service's business logic
remove comments, they have 0 useful info

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/commands/BankAccountCommands.kt
> +// Here the commands are represented by extension functions, but also can be the class member functions
same

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/aggregates/AccountAggregateState.kt
> +    }
u need to think about this TransitionFunc more, not all event fields are used

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/controller/Controller.kt
> +    fun createProject(@RequestParam userId: String, @RequestParam accountId: String) : AccountCreatedEvent {
mb body will be better

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/controller/Controller.kt
> +    @PostMapping("/close/{id}")
swap id and close, {id}/close is more RESTful

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/controller/Controller.kt
> +    fun initiateTransfer(@RequestParam accountFromId: UUID, @RequestParam accountToId: UUID, @RequestParam delta: Int) : AccountUpdatedEvent {
mb body will be better again

2023-11-20 16:58 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/controller/Controller.kt
> +    }
transfer not called, can we hide this x2 accounts logic from the handler level?

2023-11-21 08:05 UTC, fadyat commented on bank-system/src/main/kotlin/ru/quipy/aggregates/AccountAggregateState.kt
> +    var updatedAt: Long = System.currentTimeMillis()
what about creating an account and a user entity, and then using those classes here in the aggregate state

2023-11-21 17:00 UTC, DoKep2 commented on bank-system/src/main/kotlin/ru/quipy/aggregates/AccountAggregateState.kt
> +    }
how to cope with fact, that func used for **this** aggregate state and change balances for both acc

2023-11-25 10:19 UTC, closed without merging